### ISSUE TITLE
Update copyright license year to 2023

### ISSUE THREAD

**Issue by Panquesito7** [minetest-texture-packs/methro_pack#5]
CC: @Methro, up to you.

**Comment by GabrielRangel06** [comment]
> CC: @Methro, up to you.

I am going to do a PR to push all the changes including this one (taking this in mind). I forgot completely this

**Comment by GabrielRangel06** [comment]
Updating [License.md](https://github.com/minetest-texture-packs/methro_pack/blob/main/LICENSE.md) soon

**Comment by Panquesito7** [comment]
> > CC: @Methro, up to you.
> 
> I am going to do a PR to push all the changes including this one (taking this in mind). I forgot completely this

Sure. You can commit directly as well if you want. 🙂

**Comment by GabrielRangel06** [comment]
> > > CC: @Methro, up to you.
> > 
> > 
> > I am going to do a PR to push all the changes including this one (taking this in mind). I forgot completely this
> 
> Sure. You can commit directly as well if you want. 🙂

Changed already, ([Update Readme based on license's year](https://github.com/minetest-texture-packs/methro_pack/commit/3806ec9a3d7912e634ca34674684e7bfff22bb83) & [Update LICENSE based on it's year](https://github.com/minetest-texture-packs/methro_pack/commit/f924f1f1a1ace99e487c4cbddfb738548b49594d)) has been some time since then I haven't had that much time so I am comitting directly instead.

PS: PR will be postponed until I get available to do so.
